# Generated by Django 5.2.3 on 2025-06-19 06:57

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(db_index=True, max_length=255)),
                ('song_list', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['theme'], name='core_playli_theme_8adb5e_idx'), models.Index(django.db.models.functions.text.Lower('theme'), name='playlist_theme_lower_idx')],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('spotify_uri', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_song_name_717550_idx'), models.Index(django.db.models.functions.text.Lower('name'), name='song_name_lower_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_song_name_case_insensitive')],
            },
        ),
    ]
