# Generated by Django 5.2.3 on 2025-06-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_text',
        ),
        migrations.AddField(
            model_name='playlist',
            name='song_list',
            field=models.JSONField(default=list),
        ),
    ]
